set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property PACKAGE_PIN T18 [get_ports {reset}]
set_property PACKAGE_PIN V17 [get_ports {SW0}]
set_property PACKAGE_PIN W7 [get_ports {digitial_o[0]}]
set_property PACKAGE_PIN W6 [get_ports {digitial_o[1]}]
set_property PACKAGE_PIN U8 [get_ports {digitial_o[2]}]
set_property PACKAGE_PIN V8 [get_ports {digitial_o[3]}]
set_property PACKAGE_PIN U5 [get_ports {digitial_o[4]}]
set_property PACKAGE_PIN V5 [get_ports {digitial_o[5]}]
set_property PACKAGE_PIN U7 [get_ports {digitial_o[6]}]

set_property PACKAGE_PIN U2 [get_ports {anns_o[0]}]
set_property PACKAGE_PIN U4 [get_ports {anns_o[1]}]
set_property PACKAGE_PIN V4 [get_ports {anns_o[2]}]
set_property PACKAGE_PIN W4 [get_ports {anns_o[3]}]

set_property PACKAGE_PIN U16 [get_ports {leds_o[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds_o[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds_o[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds_o[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds_o[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds_o[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds_o[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digitial_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitial_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitial_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitial_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitial_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitial_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digitial_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {anns_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anns_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anns_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anns_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW0}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {SW0}]
create_clock -period 14 [get_ports clk]